services:
  vote:
    image: seyibright/vote:latest
    ports:
      - 5000:80

  result:
    image: seyibright/result:latest
    ports:
      - 5001:4000
  worker:
    image: seyibright/worker:latest
volumes:
  db-data:
networks:
  instavote:
    driver: bridge

services:
  vote:
    image: seyibright/vote:latest
    ports:
    - 5000:80
    depends_on:
    - redis
    networks:
    - instavote
  redis:
    image: redis:alpine
    networks:
    - instavote
  db:
    image: postgres:9.4
    volumes:
    - "db-data:/var/lib/postgresql/data"
    networks:
    - instavote

  result:
    image: seyibright/result:latest
    ports:
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: seyibright/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
